### ISSUE TITLE
Marker shadows not seen in component --> needs to copy and paste PNG files in your project 

### ISSUE THREAD

**Issue by jmortholand** [Orange-OpenSource/IOT-Map-Component#11]
So far, marker shadows (PNG files) are not rightly seen through the use of the component. Then markers appear on map with "broken images" behing them.

--> To bypass this issue, you need to copy PNG files contained in iotmapmanager/img and to paste them in your project (in assets/img)

**Comment by sandrinegateau** [comment]
shadows are now contained in the package
