### ISSUE TITLE
Popup title link color is blue instead of black

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/IOT-Map-Component#19]
Popup title link color is displayed blue instead of black.

![Capture d’écran 2021-04-28 à 11 09 51](https://user-images.githubusercontent.com/17381666/116378279-4676ca80-a812-11eb-8a47-2eee1d3fdce7.png)

![Capture d’écran 2021-04-28 à 11 07 43](https://user-images.githubusercontent.com/17381666/116378003-0283c580-a812-11eb-9e38-1294a25aa84f.png)

**Comment by jacques-lebourgeois** [comment]
Looks like ttill there in 2.3.0
