### ISSUE TITLE
Missing a Type to define a marker

### ISSUE THREAD

**Issue by jacques-lebourgeois** [Orange-OpenSource/IOT-Map-Component#3]
Is there any type definition for Marker like : 
```
export interface IOTMarker {
  id: string;
  location: { [0]: number; [1]: number };
  popup?: string;
  shape?: {
    shape?: string;
    color?: string;
    anchored?: boolean;
    plain?: boolean;
  };
  inner: {
    color: string;

    icon?: string;
    // *** OR ***
    label?: string;
  };
  gauge?: {
    color?: string;
    percent?: number;
  };
}
```

**Comment by sandrinegateau** [comment]
Done.
New type created () : 
IotMarker {
  id: string;
  location: {
    lat: number;
    lon: number;
  };
  layer?: string;
  popup?: string;
  status?: string;
  shape?: {
    type?: markerType;
    anchored?: boolean;
    plain?: boolean;
    color?: string;
    percent?: number;
    accuracy?: number;
  };
  inner?: {
    color?: string;

    icon?: string;
    // *** OR ***
    label?: string;
  };

}
