### ISSUE TITLE
Problem with auto zoom using markersArea

### ISSUE THREAD

**Issue by jacques-lebourgeois** [Orange-OpenSource/IOT-Map-Component#30]
We met a problem with autozoom on a cluser.

We have this definition of a cluster :
{"id":"u09","location":{"lat":48.871960972901434,"lng":2.346397452056408},"contentLabel":"Devices","childCount":4,"aggregation":[{"singularState":"Activated","pluralState":"Activated","count":3,"color":"#32c832"},{"singularState":"Initializing","pluralState":"Initializing","count":1,"color":"#32c832"}],"markersArea":{"_southWest":{"lat":48.87180808070116,"lng":2.34507473744452},"_northEast":{"lat":48.87211386510171,"lng":2.347720166668296}}}

But the zoom does not include the north bounds

**Comment by jacques-lebourgeois** [comment]
I think I found the problem : A first definition of the cluster was given (same id) : {"id":"u09","location":{"lat":48.87156997807324,"lng":2.346480432897806},"contentLabel":"Devices","childCount":4,"aggregation":[{"singularState":"Activated","pluralState":"Activated","count":3,"color":"#32c832"},{"singularState":"Initializing","pluralState":"Initializing","count":1,"color":"#32c832"}],"markersArea":{"_southWest":{"lat":48.87098699156195,"lng":2.345312800258398},"_northEast":{"lat":48.87215296458453,"lng":2.3476480655372143}}}

The cluster definition changed, but the zoom kept the previous markersArea value

**Comment by jacques-lebourgeois** [comment]
![mapzoomlight](https://user-images.githubusercontent.com/40755890/135635690-cfc7900e-89ef-4ddf-a9de-e78f06f8d431.gif)

**Comment by sandrinegateau** [comment]
Bug fixed. 
Delivered in V2.6.7
