### ISSUE TITLE
404 on GET png for poi shape

### ISSUE THREAD

**Issue by jacques-lebourgeois** [Orange-OpenSource/IOT-Map-Component#4]
When using a marker with a shape poi, I got a 404 on
Request URL: http://localhost:64215/assets/img/POI_SQR_Shadow.png
or Request URL: http://localhost:64215/assets/img/POI_SQR_PIN_Shadow.png

**Comment by sandrinegateau** [comment]
Known issue. 
For the moment, you can copy 'img' directory from node_modules/iotmapmanager/assets in your assets folder.

**Comment by sandrinegateau** [comment]
Shadows are now contained in the package. No walkaround needed.
