### ISSUE TITLE
Auto close of popup of a cluster on Map Side

### ISSUE THREAD

**Issue by jacques-lebourgeois** [Orange-OpenSource/IOT-Map-Component#55]
If you have several markers co-localized near the side of the Map with the auto clustering feature,

When you click on the cluster is is exploded to display the included marker.

But if you then click on one of the marker displayed, the popup tries to open.

But the automatic position change of the map to display the popup inside the map close the exploded cluster and indirectly close the popup.

If you click again on the cluster, it is exploded again and the previously opened popup is still opened.

![cluster_on_map_side](https://user-images.githubusercontent.com/40755890/146172980-50c58885-7cf1-429b-b779-1f0ccb0924d2.gif)

**Comment by jacques-lebourgeois** [comment]
Note that this bug is reproduced on the example provided in the Angular project at the root of the IOT-Map-Component project.
Opening a tooltip of a marker positioned in a cluster causes the cluster to close if its display moves the map.
See the screenshot of this example.
![tooltip_closed_when_map_moved](https://github.com/Orange-OpenSource/IOT-Map-Component/assets/40755890/11174b39-7808-44de-a551-ee5f60bd3ef1)

**Comment by louismaximepiton** [comment]
Hey there,

I'm new to this project but I managed to solve the issue by commenting the line 3387-3389 inside `/src/iotMapManager/node_modules/leaflet/dist/leaflet-src.js` (inside `flyTo > frame`). I haven't studied all the impacts it has on the behavior of the lib or whatever but it can be a starting point to dig.

**Comment by jacques-lebourgeois** [comment]
Do you mean it may be a leaflet bug ? Or it may alse be a preventDefault() or stopPropagation() omitted in IotMapComponent ?

**Comment by julien-deramond** [comment]
We don't know yet, this is a starting point. We need to dig into the Leaflet repository to check if it's a bug or not, and depending on the results, see how we can override it directly in the IoT Map Component library. We'll keep you in touch in this issue :)
