### ISSUE TITLE
Compatibility with Boosted 4 and 5

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/IOT-Map-Component#58]
Check the compatibility of this project with both Boosted 4 and 5.
See https://github.com/Orange-OpenSource/IOT-Map-Component/blob/master/package.json where Boosted 4 is declared.

**Comment by louismaximepiton** [comment]
I just tried the test project with the latest version of Boosted (5.3.3) and I couldn't spot any regression. I can't see any relation between Boosted CSS and iotMap CSS, same for Js so I think we're fine using Boosted v5.
The only use of Boosted I could detect is on the test app to center texts and map.

**Comment by julien-deramond** [comment]
Yep, the `package.json` of the library is not dependent on any Boosted versions. All the classes present in the library are not based on Boosted ones.

> The only use of Boosted I could detect is on the test app to center texts and map.

Same.

This issue can be closed IMO too.
